version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: internhub-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: internhub
    volumes:
      - mongodb_data:/data/db
    networks:
      - internhub-network

  backend:
    build: ./backend
    container_name: internhub-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/internhub
      JWT_SECRET: your-secret-key-here
      PORT: 5000
      NODE_ENV: production
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - internhub-network

  frontend:
    build: .
    container_name: internhub-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000
    networks:
      - internhub-network

volumes:
  mongodb_data:
    driver: local

networks:
  internhub-network:
    driver: bridge 